# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1ae32e28932e8d6092345bc022fbb29aa2777c3fc161821ae18f136770e1803ae75ea12708e0c8a8bf4170ec31aafa9efd930a82c952287699621e2480f790

test:
  secret_key_base: 232afb048f0342437eae8e8fac17e89c62817c4e13133df925eadbb29d4d0a9cb458beb8c15afe5d368433705eec7a373bd6b399de6419cb37234459f8b167a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
